### ISSUE TITLE
Portable Mode

### ISSUE THREAD

**Issue by smaragdus** [bluegrams/Colora#1]
Currently Colora (as of version 0.1.0.18076) saves settings in AppData:

`C:\Users\UserName\AppData\Local\Bluegrams\Colora.exe_Url_uziftv51nxhcykh1tjrwbwaxxnjhbotk\0.1.0.18076\user.config`

For users of portable software it would be handy if Colora provides a way to save settings not in AppData but in program folder. This may be implemented in a variety of ways, just to suggest few for example:

- Command-line parameter- if Colora is started for example with this argument - "Colora.exe --portable" it saves settings in program folder;
- On program start Colora checks its program folder for "user.config"and if it is present Colora uses it;
- Portable flag- a file in program folder (for example- "Portable", "Portable.txt") serves as a trigger for portable mode;
- Empty folder- a sub-folder in program folder (for example "Data") serves as a trigger for portable mode;

If there is an option to save data and settings in program folder and not in AppData users would be able to use Colora from external drives on other machines with all its data and settings.

**Comment by alxnull** [comment]
Thanks for the idea. I'll consider the options and see what I can implement as soon as I find the time to do it (which still may take a week or two as I'm pretty busy at the moment).

**Comment by smaragdus** [comment]
@bluegrams 
Thanks for your response. If you add an option to run Colora in portable mode I may write a short review about it at a website dedicated to portable freeware- the program is nice and may be useful to many people.
Regards

**Comment by alxnull** [comment]
@smaragdus I have actually taken up your idea and implemented some support for portable applications in my project at https://github.com/bluegrams/MiniAppManager because that library handles the basic settings for Colora (and possibly for other apps).

So, the support for portable mode now looks like this :
* A 'real' portable-only version of Colora (I will release that on Sourceforge very soon)
* The command line option '--portable' for the installer based version (This option will be available in the next installer based release)

More about the basic principle of the portable mode can be found [here](https://github.com/bluegrams/MiniAppManager/wiki/Portable-Mode).

**Comment by smaragdus** [comment]
@bluegrams 
Thank you for taking my suggestion so seriously and for the good write-up about [Portable Mode](https://github.com/bluegrams/MiniAppManager/wiki/Portable-Mode). For me portability means flexibility- it gives the users the freedom to choose how and where settings are saved. Portability also means better usability- I prefer to rely upon programs which I can carry with me and use on any machine without the need of installing anything and without leaving traces and junk behind. You can rely on me for testing if needed. So far I have only tested and used [Colora](https://sourceforge.net/projects/colora/) and because I liked it I opened this issue. When I have time I may have a look at your other projects as well.
Regards

**Comment by alxnull** [comment]
@smaragdus Thank you for your suggestion. I have now uploaded the portable version on Sourceforge: https://sourceforge.net/projects/colora/files/Colora%20v.0.1.0/ (Colora-Portable.zip), so you may have a look and review it.

**Comment by smaragdus** [comment]
@bluegrams 
I tested the portable version of **Colora**, it is really portable, thank you. As I promised I wrote a short introduction at The Portable Freeware Forum- you can find it [here](https://www.portablefreeware.com/forums/viewtopic.php?f=4&t=23777). I hope I have not missed something important. I wrote that **Colora** runs on Windows 7 and higher, is that right?

**Comment by smaragdus** [comment]
Since now **Colora** has portable version I will close this issue.

**Comment by alxnull** [comment]
@smaragdus Thanks for your detailed review. 
I just realized that I made a mistake in the description because Colora actually requires .NET Framework **4.6** or higher, I'm sorry. I tested it on Windows 7 and 10 but it should even run on Vista (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies).

**Comment by smaragdus** [comment]
@bluegrams 
Thanks for the clarification, I updated the requirements accordingly.
